### PR TITLE
Devops cleanup

### LINKED ISSUE #57: Refactor and clean up
Squeaky clean plz
- [x] Make sure namespaces are consistant and proper
- [x] Code of higher quality (in terms of functionality and cleanliness)
- [x] Remove Unused projects
- [x] Docker and docker-compose config
    - [x] Persist database between shutdowns
    - [x] Close ports to DB in docker compose (fixed by making a development environment)
    - [x] Connection string from docker compose (config file or docker-compose.yml)
- [x] DevOps stuff (don't ask me what)
- [x] Etc.

### PR DESCRIPTION
**Pull request by jlndk**
Closes #57 
This PR fixes the "devops related" tasks of the #57  issue, which primarily revolves around docker and docker compose.

One of the substantial changes is the addition of a development environment. This is defined in the docker-compose.yml file. Therefore the production environment is now defined in the file `docker-compose.prod.yml`, and can be used by suffixing the docker-compose command with the -f flag (example: `docker-compose -f docker-compose.prod.yml up -d`.

The configuration has also been streamlined so that all environment specific configuation is defined in the docker-compose files.

### CODE REVIEW

**Comment by tobloef** [comment]
nice

**Review by Hjaltesorgenfrei — COMMENTED** [review]
Looks fine. Have you run it on a server?

**Comment by jlndk** [comment]
I have run it on my own machine, which is also based on ubuntu 18.04 LTS, so it should be pretty similar. We can however run it on a server first of you want.

Futhermore since the abstractions are made through docker they should translate pretty well to a server environment.

**Comment by jlndk** [comment]
@Duckapple  and I have desided to test it on his machine. If it runs I think that is sufficient for now. If we encounter errors while deploying we'll create a new bugfix/hotfix PR for that

**Comment by jlndk** [comment]
image

It appears that we maybe also should persist these encryption keys in a volume

**Comment by Duckapple** [comment]
I tried building the test environment, and it didn't work the first time I ran it. It produced the following error.

```
database_1  | 2020-02-24 13:22:59.628 UTC [1] LOG:  database system is ready to accept connections
database_1  | 2020-02-24 13:23:11.034 UTC [62] FATAL:  database "MiniTwit" does not exist
database_1  | 2020-02-24 13:23:11.049 UTC [63] FATAL:  database "MiniTwit" does not exist
webapp_1    | fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
webapp_1    |       Failed executing DbCommand (30,008ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
webapp_1    |       CREATE DATABASE "MiniTwit";
webapp_1    | crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
webapp_1    |       Application startup exception
webapp_1    | Npgsql.NpgsqlException (0x80004005): Exception while reading from stream
webapp_1    |  ---> System.IO.IOException: Unable to read data from the transport connection: Connection timed out.
```

It seems to be a problem with race conditions, as the PostgreSQL instance has not initialized the tables correctly. 
It *did* work once I ran docker down and then docker up again, so there's your temp-fix.

**Comment by jlndk** [comment]
We should also use a tagged version of postgres (version 12)

**Comment by Duckapple** [comment]
> I tried building the test environment, and it didn't work the first time I ran it. It produced the following error.

I could not reproduce this anomaly even after pruning everything, so I guess it is fine by me.

**Review by Duckapple — APPROVED** [review]
I like the changes, making things more explicit and working and stuff.

**Pull request merged**
