### PR TITLE
3.0 Scaling and Loadbalancing

### LINKED ISSUE #218: 3.0 - Process Scaling & Load Balancing

### PR DESCRIPTION
**Pull request by jlndk**
close #218

### CODE REVIEW

**Review by tobloef — DISMISSED** [review]
- Tror ikke man behøver komma i "easy-to-use interface, compared."
- "when connecting to the web application simply stuck with the old setup" Der mangler nok nogle ord.

**Comment by Hjaltesorgenfrei** [comment]
"We" needs to be removed from all of this.

**Comment by jlndk** [comment]
There is now only 5 "we"s left. If you want them removed, please say so.

**Comment by Hjaltesorgenfrei** [comment]
Remoce them please

**Review by Hjaltesorgenfrei — APPROVED** [review]

**Pull request merged**
