### PR TITLE
Follow users

### LINKED ISSUE #81: Follow button on website
We missing the follow button website.

### PR DESCRIPTION
**Pull request by tobloef**
You can now follow and unfollow users from their timeline.

### CODE REVIEW

**Comment by tobloef** [comment]
We need some tests!

**Comment by tobloef** [comment]
We need some tests!

**Comment by tobloef** [comment]
Fixes #88 btw

**Review by jlndk — APPROVED** [review]

**Review by Hjaltesorgenfrei — APPROVED** [review]
tenor

**Pull request merged**
